import type { CompanyFundamentals } from "./types";

export const COMPANIES: CompanyFundamentals[] = [
  {
    ticker: "TCS",
    name: "Tata Consultancy Services",
    sector: "IT Services",
    revenue: 240893,
    netMargin: 19.2,
    debtEquity: 0.08,
    beta: 0.74,
    roce: 51.4,
    currentRatio: 2.5,
    interestCoverage: 58.6,
    returnOnNewCapital: 24,
    cashflowGrowth: 9,
  },
  {
    ticker: "INFY",
    name: "Infosys",
    sector: "IT Services",
    revenue: 153670,
    netMargin: 16.5,
    debtEquity: 0.09,
    beta: 0.82,
    roce: 39.8,
    currentRatio: 2.1,
    interestCoverage: 42.3,
    returnOnNewCapital: 21,
    cashflowGrowth: 8,
  },
  {
    ticker: "RELIANCE",
    name: "Reliance Industries",
    sector: "Conglomerate / Energy",
    revenue: 901064,
    netMargin: 8.1,
    debtEquity: 0.44,
    beta: 1.12,
    roce: 9.6,
    currentRatio: 1.1,
    interestCoverage: 5.4,
    returnOnNewCapital: 13,
    cashflowGrowth: 7,
  },
  {
    ticker: "HDFCBANK",
    name: "HDFC Bank",
    sector: "Banking",
    revenue: 407995,
    netMargin: 27.8,
    debtEquity: 1.6,
    beta: 0.96,
    roce: 7.1,
    currentRatio: 1.0,
    interestCoverage: 1.9,
    returnOnNewCapital: 15,
    cashflowGrowth: 11,
  },
  {
    ticker: "WIPRO",
    name: "Wipro",
    sector: "IT Services",
    revenue: 89760,
    netMargin: 12.4,
    debtEquity: 0.21,
    beta: 0.88,
    roce: 18.2,
    currentRatio: 2.4,
    interestCoverage: 14.7,
    returnOnNewCapital: 14,
    cashflowGrowth: 5,
  },
  {
    ticker: "TATASTEEL",
    name: "Tata Steel",
    sector: "Metals & Mining",
    revenue: 229171,
    netMargin: -3.2,
    debtEquity: 1.18,
    beta: 1.34,
    roce: 6.4,
    currentRatio: 0.8,
    interestCoverage: 2.1,
    returnOnNewCapital: 8.5,
    cashflowGrowth: 4,
  },
  {
    ticker: "SUNPHARMA",
    name: "Sun Pharmaceutical",
    sector: "Pharmaceuticals",
    revenue: 47973,
    netMargin: 19.6,
    debtEquity: 0.11,
    beta: 0.59,
    roce: 17.9,
    currentRatio: 2.0,
    interestCoverage: 21.4,
    returnOnNewCapital: 17,
    cashflowGrowth: 9,
  },
  {
    ticker: "MARUTI",
    name: "Maruti Suzuki India",
    sector: "Automobiles",
    revenue: 141858,
    netMargin: 9.1,
    debtEquity: 0.02,
    beta: 0.83,
    roce: 18.6,
    currentRatio: 0.9,
    interestCoverage: 39.5,
    returnOnNewCapital: 16,
    cashflowGrowth: 8,
  },
  {
    ticker: "ONGC",
    name: "Oil & Natural Gas Corp",
    sector: "Oil & Gas",
    revenue: 643688,
    netMargin: 6.4,
    debtEquity: 0.42,
    beta: 1.21,
    roce: 14.8,
    currentRatio: 0.7,
    interestCoverage: 9.8,
    returnOnNewCapital: 12,
    cashflowGrowth: 3,
  },
  {
    ticker: "ASIANPAINT",
    name: "Asian Paints",
    sector: "Consumer / Paints",
    revenue: 35495,
    netMargin: 13.0,
    debtEquity: 0.07,
    beta: 0.66,
    roce: 32.7,
    currentRatio: 1.7,
    interestCoverage: 28.6,
    returnOnNewCapital: 20,
    cashflowGrowth: 7,
  },
];

export function getCompany(ticker: string): CompanyFundamentals | undefined {
  return COMPANIES.find((c) => c.ticker === ticker || c.name === ticker);
}
