/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerdictRouteImport } from './routes/verdict'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as BondRouteImport } from './routes/bond'
import { Route as IndexRouteImport } from './routes/index'

const VerdictRoute = VerdictRouteImport.update({
  id: '/verdict',
  path: '/verdict',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const BondRoute = BondRouteImport.update({
  id: '/bond',
  path: '/bond',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bond': typeof BondRoute
  '/compare': typeof CompareRoute
  '/verdict': typeof VerdictRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bond': typeof BondRoute
  '/compare': typeof CompareRoute
  '/verdict': typeof VerdictRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bond': typeof BondRoute
  '/compare': typeof CompareRoute
  '/verdict': typeof VerdictRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bond' | '/compare' | '/verdict'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bond' | '/compare' | '/verdict'
  id: '__root__' | '/' | '/bond' | '/compare' | '/verdict'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BondRoute: typeof BondRoute
  CompareRoute: typeof CompareRoute
  VerdictRoute: typeof VerdictRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verdict': {
      id: '/verdict'
      path: '/verdict'
      fullPath: '/verdict'
      preLoaderRoute: typeof VerdictRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bond': {
      id: '/bond'
      path: '/bond'
      fullPath: '/bond'
      preLoaderRoute: typeof BondRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BondRoute: BondRoute,
  CompareRoute: CompareRoute,
  VerdictRoute: VerdictRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
